name: Java CI with Gradle

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.2
      uses: actions/setup-java@v2
      with:
        java-version: '14.0.2'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #  working-directory: LibrarySystem-Backend
    #- name: Build with Gradle
    #  run: ./gradlew build
    #  working-directory: LibrarySystem-Backend
