name: Java CI with Gradle

on:
  push:
<<<<<<< HEAD
    branches: 
      - master
  pull_request:
    branches: 
      - master
=======
    branches: [ master ]
  pull_request:
    branches: [ master ]
>>>>>>> origin/ramin-crud-interfaces

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16.0.2
      uses: actions/setup-java@v2
      with:
        java-version: '16.0.2'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: LibraryService-Backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: LibraryService-Backend
