name: Deploying Vue to Heroku

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
          
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - name: Building the project
      - run: npm run build
      - uses: akhileshns/heroku-deploy@v3.12.12
      
        with:
          args: deploy --only hosting
          heroku_api_key: 6a5c0620-a1f0-42ee-bee7-40ba632aef4d
          heroku_app_name: "libraryservice-backend-g13"
          heroku_email: "gabrielle.halpin@mail.mcgill.ca"
