name: Deploying Vue to Heroku

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
          
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: initial Setup
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install npm wrapper
        working-directory: ./LibraryService-Frontend
        run: npm install
      - name: Building the project
        working-directory: ./LibraryService-Frontend
        run: npm run build
